version: "3.8"
services:
  db:
    image: postgres:14
    container_name: db_app
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    env_file:
      - .env

  app:
    build:
      context: .
    env_file:
      - .env
    container_name: fastapi_app
    command: "gunicorn main:app --workers 1 --worker-class uvicorn.workers.UvicornWorker --bind=0.0.0.0:8000 --reload"
    ports:
      - "5000:8000"
    depends_on:
      - db
    volumes:
      - ./:/fastapi_app

volumes:
  postgres_data:
